# Generated by Django 4.2.5 on 2024-09-29 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisOfUnitaryPricesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Analisis de precios unitarios',
                'verbose_name_plural': 'Analisis de precios unitarios',
            },
        ),
        migrations.CreateModel(
            name='CitiesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=30, verbose_name='Nombre de ciudad')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='CompamiesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nit', models.CharField(blank=True, default='', max_length=15, verbose_name='NIT')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('legal_rep', models.CharField(blank=True, default='', max_length=100, verbose_name='Representante legal')),
                ('web_link', models.CharField(blank=True, default='', max_length=100, verbose_name='Pagina Web')),
                ('email', models.CharField(max_length=100, verbose_name='Correo electrónico')),
                ('cellphone', models.CharField(blank=True, default='', max_length=15, verbose_name='Número de telefono')),
                ('is_auditor', models.BooleanField(default=False, verbose_name='Es interventoria?')),
                ('fk_id_cities', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APUs.citiesmodel', verbose_name='Ciudad y país')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
            },
        ),
        migrations.CreateModel(
            name='CountriesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=30, verbose_name='Nombre de pais')),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
            },
        ),
        migrations.CreateModel(
            name='ProjectsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100, verbose_name='Nombre')),
                ('cod_obra', models.CharField(blank=True, max_length=30, verbose_name='Código de obra')),
                ('object', models.CharField(blank=True, max_length=1000, verbose_name='Objeto del proyecto')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('date_bidding', models.DateTimeField(blank=True, verbose_name='Fecha de licitacion')),
                ('n_bidding', models.CharField(blank=True, max_length=20, verbose_name='Número de licitación')),
                ('date_start', models.DateTimeField(verbose_name='Fecha inicio de obra')),
                ('date_end', models.DateTimeField(blank=True, verbose_name='Fecha fin de obra')),
                ('addres', models.CharField(max_length=100, verbose_name='Diercción de obra')),
                ('is_direct_cost', models.BooleanField(default=False, verbose_name='Es costo directo?')),
                ('administration', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Administración')),
                ('eventuality', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Imprevistos')),
                ('utility', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Utilidad')),
                ('fk_id_auditor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='auditor_project', to='APUs.compamiesmodel', verbose_name='Interventoria')),
                ('fk_id_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APUs.citiesmodel', verbose_name='Ciudad')),
                ('fk_id_companie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companie_project', to='APUs.compamiesmodel', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='TypeMoneyModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('money', models.CharField(max_length=10, verbose_name='Moneda')),
                ('money_simb', models.CharField(max_length=2, verbose_name='Simbolo de moneda')),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
            },
        ),
        migrations.CreateModel(
            name='TypeProyectModels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=30, verbose_name='Tipo de proyecto')),
            ],
            options={
                'verbose_name': 'Tipo de proyecto',
                'verbose_name_plural': 'Tipos de proyecto',
            },
        ),
        migrations.CreateModel(
            name='TypeSuppliesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=15, verbose_name='Insumos')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
            },
        ),
        migrations.CreateModel(
            name='UnitsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=10, verbose_name='Simbolo')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.CreateModel(
            name='WorkBreakdownStructureModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.IntegerField(default=1, verbose_name='Grado')),
                ('description', models.CharField(max_length=500, verbose_name='Descripción')),
                ('cant', models.DecimalField(decimal_places=10, default=0.0, max_digits=20, verbose_name='Cantidad')),
                ('date_edit', models.DateTimeField(auto_now=True, verbose_name='Fecha editado')),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inicio')),
                ('date_end', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de fin')),
                ('key_username_item', models.CharField(max_length=10, verbose_name='Clave de usuario')),
                ('fk_id_analyst_of_unitary_prices', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='APUs.analysisofunitarypricesmodel', verbose_name='APU')),
                ('fk_id_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APUs.projectsmodel', verbose_name='Proyecto')),
                ('fk_id_user_add', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'EDS',
                'verbose_name_plural': 'EDS',
            },
        ),
        migrations.CreateModel(
            name='SuppliesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50, verbose_name='Descripción')),
                ('data_aditional', models.CharField(blank=True, default='', max_length=100, verbose_name='Información adicional')),
                ('date_uplated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=13, verbose_name='Precio')),
                ('fk_id_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APUs.citiesmodel', verbose_name='Ciudad')),
                ('fk_id_type_supplies', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APUs.typesuppliesmodel', verbose_name='Insumo')),
                ('fk_id_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APUs.unitsmodel', verbose_name='Unidad')),
                ('fk_id_user_create', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
            },
        ),
        migrations.CreateModel(
            name='SuppliesInAPUModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=13, verbose_name='Precio')),
                ('cant', models.DecimalField(decimal_places=10, default=0.0, max_digits=30, verbose_name='Cantidad')),
                ('fk_id_APU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APUs.analysisofunitarypricesmodel', verbose_name='Usuario')),
                ('fk_id_supplies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APUs.suppliesmodel', verbose_name='Insumo')),
            ],
            options={
                'verbose_name': 'Insumos - APU',
                'verbose_name_plural': 'Insumos - APU',
            },
        ),
        migrations.AddField(
            model_name='projectsmodel',
            name='fk_id_money',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APUs.typemoneymodel', verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='projectsmodel',
            name='fk_id_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APUs.typeproyectmodels', verbose_name='Tipo de proyecto'),
        ),
        migrations.AddField(
            model_name='projectsmodel',
            name='fk_id_usercreate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Nombre de usurio creador'),
        ),
        migrations.CreateModel(
            name='KeySupplieProjectModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key_user', models.CharField(max_length=10, verbose_name='Clave')),
                ('fk_id_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APUs.projectsmodel', verbose_name='Proyecto')),
                ('fk_id_supplies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APUs.suppliesmodel', verbose_name='Insumo')),
            ],
            options={
                'verbose_name': 'Clave de insumo',
                'verbose_name_plural': 'Claves de insumos',
            },
        ),
        migrations.AddField(
            model_name='citiesmodel',
            name='fk_id_countries',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APUs.countriesmodel', verbose_name='Pais'),
        ),
        migrations.AddField(
            model_name='analysisofunitarypricesmodel',
            name='fk_id_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APUs.citiesmodel', verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='analysisofunitarypricesmodel',
            name='fk_id_type_project',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='APUs.typeproyectmodels', verbose_name='Tipo de proyecto'),
        ),
        migrations.AddField(
            model_name='analysisofunitarypricesmodel',
            name='fk_id_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APUs.unitsmodel', verbose_name='Unidad'),
        ),
        migrations.AddField(
            model_name='analysisofunitarypricesmodel',
            name='fk_id_user_create',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador'),
        ),
    ]
